name: Nightly Promotion

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'nightly'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Merge nightly into production
        run: |
          git checkout -B production origin/production
          git merge --no-ff origin/nightly -m "CI: promote nightly to production"
          git push origin production
